---
title: "lemonutil_examples"
author: "Lemon Reimer"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
# devtools::install_github("lemonlinn/lemonutil", upgrade = "never") to download/update
library(lemonutil)
```

```{r df}
# making example dataset
cat_var <- c(1,2,1,1,2,2,1,1,1,2,2,2)
con_var <- c(1,5,3,4,2,5,4,3,1,1,2,5)
d <- data.frame("cat_var"=cat_var, "con_var"=con_var)
```

# unitable

```{r basic unitable}
lemonutil::unitable(d, d$cat_var)
uni_tbl1 = lemonutil::unitable(d, d$con_var)
uni_tbl1
```

```{r unitable with options}
uni_tbl2 = lemonutil::unitable(d, d$con_var, namecol = c("disagree", "kinda disagree", "neither", "kinda agree", "agree"), text = "Do you agree or disagree?", title = "Table distribution of con_var")
uni_tbl2
```

```{r unitable with min/max option}
# If your data doesn't contain available response options because nobody chose them, but you still want that option shown in the table, use the optional minval and maxval options.
# For example, the question had 7 categories to choose from, but 6 and 7 were never chosen:

lemonutil::unitable(d, d$con_var, minval = 1, maxval = 7)

```

# crosstable

```{r basic crosstable}
cross_tbl1 = lemonutil::crosstable(d, "con_var", "cat_var")
cross_tbl1
```

```{r crosstable with options}
cross_tbl2 = lemonutil::crosstable(d, "con_var", "cat_var", x_names = c("disagree", "kinda disagree", "neither", "kinda agree", "agree"), y_names = c("yes", "no"))
cross_tbl2
```

# flex2df

```{r basic unitbl df}
uni_df1 = lemonutil::flex2df(uni_tbl1, tbl_type = "unitable")
head(uni_df1)
```

```{r options unitbl df}
uni_df2 = lemonutil::flex2df(uni_tbl2, tbl_type = "unitable")
uni_df2
```

```{r basic crosstbl df}
cross_df1 = lemonutil::flex2df(cross_tbl1, tbl_type = "crosstable")
cross_df1
```

```{r options crosstbl df}
cross_df2 = lemonutil::flex2df(cross_tbl2, tbl_type = "crosstable")
head(cross_df2)
```

# meanBoxplot

```{r basic boxplot}
g = lemonutil::meanBoxplot(d, cat_var, con_var)
g
```

```{r adding to boxplot}
library(ggplot2)

g + geom_jitter(aes(color="red"), alpha=0.5, show.legend = F, width = 0.1) + 
  labs(x="Binary Variable", y="Ordinal/Continuous Variable") + 
  scale_x_discrete(labels=c("1" = "Yes", "2" = "No"))
```


